name: CI/CD Pipeline for Streamlit App

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12  # Specify your Python version
  # Include other environment variables if needed
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build the Streamlit app
        run: |
          nohup streamlit run app.py &  # Start the Streamlit app
          sleep 10  # Wait for the app to start
          curl -f http://localhost:8501  # Check if the app is running

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: streamlit-app-artifact  # Name of the artifact
          path: ./  # Adjust the path to where your Streamlit app files are located

  deploy:
    needs: build  # Wait for the build job to finish before deploying

    runs-on: ubuntu-latest

    permissions:
      pages: write  # Grant permissions for Pages deployment
      id-token: write  # Necessary for deployment verification

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # Only deploy on push events
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: streamlit-app-artifact  # Reference the artifact created in the build job
